# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            developerro
tagline:          'El blog de Fernando Escolar'
description:      'cuando en mi m√°quina tampoco funciona...'
url:              http://fernandoescolar.github.io
baseurl:          http://fernandoescolar.github.io/
icon:           your site icon path # /assets/img/icon.png [best 300px X 300px]

author:
  name:           'Fernando Escolar'
  url:            https://twitter.com/fernandoescolar
  twitter:        fernandoescolar
  google_plus:    FernandoEscolar
  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fernandoescolar
